---
- name: Configure borgbackup
  block:
    - name: Ensure mount folder exists
      ansible.builtin.file:
        path: "{{ borgbackup_backup_device_mountpoint }}"
        state: directory
        mode: "0700"
        owner: "{{ borgbackup_user }}"
        group: "{{ borgbackup_group }}"
      become: true

    - name: Ensure config folder exists
      ansible.builtin.file:
        path: "{{ borgbackup_config_dir }}"
        state: directory
        mode: "0700"
        owner: "{{ borgbackup_user }}"
        group: "{{ borgbackup_group }}"
      become: true

    - name: Ensure backup script exists
      ansible.builtin.template:
        src: "backup.sh.j2"
        dest: "{{ borgbackup_config_dir }}/backup.sh"
        mode: "0700"
        owner: "{{ borgbackup_user }}"
        group: "{{ borgbackup_group }}"
      become: true

    - name: Ensure backup patterns exist
      ansible.builtin.template:
        src: "borgPatterns.lst.j2"
        dest: "{{ borgbackup_config_dir }}/borgPatterns.lst"
        mode: "0600"
        owner: "{{ borgbackup_user }}"
        group: "{{ borgbackup_group }}"
      become: true

    - name: Create keyfile from /dev/urandom if it does not exist
      ansible.builtin.command:
        cmd: "dd if=/dev/urandom of={{ borgbackup_backup_device_keyfile }} bs=1024 count=4"
        creates: "{{ borgbackup_backup_device_keyfile }}"
      become: true

    - name: Set file permissions on keyfile
      ansible.builtin.file:
        path: "{{ borgbackup_backup_device_keyfile }}"
        mode: "0600"
        owner: "{{ borgbackup_user }}"
        group: "{{ borgbackup_group }}"
      become: true
