---
- name: Create automount udev rule
  block:
    - name: Copy udev files
      ansible.builtin.template:
        src: "99-BackupDisk.rules.j2"
        dest: "/etc/udev/rules.d/99-BackupDisk.rules"
        owner: root
        group: root
        mode: "0644"
      notify: Reload udev rules
      become: true
