---
- name: Create automount systemd services
  block:
    - name: Copy systemd services
      ansible.builtin.template:
        src: "{{ service.src }}"
        dest: "{{ service.dest }}"
        owner: root
        group: root
        mode: "{{ service.mode }}"
      with_items:
        - {
            src: "mnt-backup.mount.j2",
            dest: "/etc/systemd/system/mnt-backup.mount",
            mode: "0644",
          }
        - {
            src: "backup-disk-decrypt.service.j2",
            dest: "/etc/systemd/system/backup-disk-decrypt.service",
            mode: "0644",
          }
      loop_control:
        loop_var: service
      notify: Reload systemd daemon
      become: true
